require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native-permissions/scripts/setup'

platform :ios, '15.0'
install! 'cocoapods', :deterministic_uuids => false

source 'https://cdn.cocoapods.org/'
source 'https://github.com/SumSubstance/Specs.git'
# ENV['IDENSIC_WITH_MRTDREADER'] = 'true'
ENV['IDENSIC_WITH_VIDEOIDENT'] = 'true'

# Ensure `OpenSSL-Universal` dependency to be included in Release builds
# Commented out to avoid version conflicts - let CocoaPods resolve automatically
# if ENV['IDENSIC_WITH_MRTDREADER']
#   pod 'OpenSSL-Universal', :configurations => ['Debug', 'Release']
# end

setup_permissions([
  'Camera',
  'FaceID',
  'LocationWhenInUse',
  'PhotoLibrary',
  'PhotoLibraryAddOnly',
])

target 'FedevProject' do
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => false, # Hermes is now enabled by default. Disable by setting this flag to false.
    :fabric_enabled => flags[:fabric_enabled],
    :flipper_configuration => (ENV['FLIPPER'] == '1' ? FlipperConfiguration.enabled : FlipperConfiguration.disabled),
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  pod 'PiwikPROSDK', '1.1.3'

  pod 'GoogleUtilities', :modular_headers => true
  pod 'FirebaseCore', :modular_headers => true
  
  target 'FedevProjectTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    react_native_post_install(
      installer,
      :mac_catalyst_enabled => false
    )
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['ENABLE_BITCODE'] = 'NO' # NMA SDK does not support Bitcode
      end
    end
    __apply_Xcode_12_5_M1_post_install_workaround(installer)

    # 解決RCT错误
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', '_LIBCPP_ENABLE_CXX17_REMOVED_UNARY_BINARY_FUNCTION']
      end
    end

    # 解決Flipper错误
    installer.pods_project.targets.each do |target|
      if target.name == 'Flipper'
        file_path = 'Pods/Flipper/xplat/Flipper/FlipperTransportTypes.h'
        contents = File.read(file_path)
        unless contents.include?('#include <functional>')
          File.open(file_path, 'w') do |file|
            file.puts('#include <functional>')
            file.puts(contents)
          end
        end
      end
    end
  end

end
